### PR TITLE
Merge identical lines that overlap in time

### LINKED ISSUE #5: Ignore drawing commands & duplicate lines
I don't think drawing commands are within the scope of this script, so they should probably be skipped. Example:

### PR DESCRIPTION
**Pull request by christoph-heinrich**
So far such lines only got merged if they were right after each other, but there are situations where they overlap.

Fixes https://github.com/christoph-heinrich/mpv-subtitle-lines/issues/5#issuecomment-1965590537

### CODE REVIEW

**Comment by FichteFoll** [comment]
I'll try this out when I notice a file with many duplicate script lines again and see if it fixes the problem entirely.

**Comment by FichteFoll** [comment]
So, it's an improvement but the times are still messed up. These lines are not all visible at the same time.

Before:

|Before|After|
|:-|:-|
|||

**Comment by FichteFoll** [comment]
It seems like mpv creates new "lines" with all currently visible lines whenever a new line appears, which obviously then causes repititions, but the algorithm of mpv-subtitle-lines to merge these (and the timestamps) is too aggressive.

For context, the "ShanFro-Theater" line is visible the entire time.

**Comment by christoph-heinrich** [comment]
I'm pretty sure in this case mpv simply provides 22:41 and 23:47 for `sub-start` and `sub-end` for all those lines ~and I don't think there is anything I can do about that~.

I could try guessing the real start time via the current playback time and the sub-delay, but the end time is tricky.
Maybe I can compare the lines I get for each step with the ones from the previous step, and the missing lines then get the current time as their end time. 

That's pretty hacky though, not sure that's worth it.

FWIW I tried the start-time hack. (I modified the subtitle file so that the slf theater announcement sticks around, because it didn't have that constant text like yours)

```diff
diff --git a/subtitle-lines.lua b/subtitle-lines.lua
index aa6d4ea..5a2fd0a 100644
--- a/subtitle-lines.lua
+++ b/subtitle-lines.lua
@@ -52,7 +52,7 @@ local sub_strings_available = {
 
 local sub_strings = sub_strings_available.primary
 local function get_current_subtitle()
-    local start = mp.get_property_number(sub_strings.start)
+    local start = mp.get_property_number('playback-time') - mp.get_property_number('sub-delay')
     local stop = mp.get_property_number(sub_strings['end'])
     local text = mp.get_property(sub_strings.text)
     local lines = text and text:match('^[%s\n]*(.-)[%s\n]*$') or ''
```

image

**Comment by christoph-heinrich** [comment]
After sleeping it over, I've given the end time correction a try.

It now automatically tries to correct start and end times of lines if inaccuracies are detected.

image

**Comment by FichteFoll** [comment]
Thanks, this appears to work just fine (for my test cases). :pray:

**Pull request merged**
